{% set name = "pymmcore" %}
{% set version = "11.1.1.71.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymmcore-{{ version }}.tar.gz
  sha256: 4338facb77f4a52b03ed2e23cb0f2834c0331d66aa55940adf874a2293118e07

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - numpy >=1.23.5
    - pip
    - python
    - swig
  run:
    - python

test:
  imports:
    - pymmcore
  commands:
    - pip list
    - pip check
    - python -c "import pymmcore;mmc = pymmcore.CMMCore();print(mmc)"
  requires:
    - pip

about:
  home: https://github.com/micro-manager/pymmcore
  summary: Python bindings for MMCore, Micro-Manager's device control layer
  license: LGPL-2.1-only AND BSD-3-Clause
  license_file:
    - LICENSE.txt
    - MMDevice_license.txt
    - MMCore_license.txt

extra:
  recipe-maintainers:
    - goanpeca
    - marktsuchida
    - tlambert03
