{% set name = "pymmcore" %}
{% set version = "12.5.0.75.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymmcore-{{ version }}.tar.gz
  sha256: c78670ff99ea2a4424d41eea7f0f0b6059053689af7700a5b19815fa8dde8390

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - numpy >=2.0.0
    - pip
    - python
    - swig ==4.4.0
    - meson-python
    - ninja
  run:
    - python
    - numpy >=1.26

test:
  imports:
    - pymmcore
  commands:
    - pip list
    - pip check
    - python -c "import pymmcore;mmc = pymmcore.CMMCore();print(mmc)"
  requires:
    - pip

about:
  home: https://github.com/micro-manager/pymmcore
  summary: Python bindings for MMCore, Micro-Manager's device control layer
  license: LGPL-2.1-only AND BSD-3-Clause
  license_file:
    - LICENSE.txt
    - MMDevice_license.txt
    - MMCore_license.txt

extra:
  recipe-maintainers:
    - goanpeca
    - marktsuchida
    - tlambert03
