{% set name = "pymmcore" %}
{% set version = "10.1.1.70.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymmcore-{{ version }}.tar.gz
  sha256: d522b167daf0eb39076a0e83851ffa20ec1844d965cd3457350c6f1965f4bc47

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - numpy
    - pip
    - python
    - swig
  run:
    - {{ pin_compatible('boost-cpp') }}
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pymmcore
  commands:
    - pip list
    - pip check
    - python -c "import pymmcore;mmc = pymmcore.CMMCore();print(mmc)"
  requires:
    - pip

about:
  home: https://github.com/micro-manager/pymmcore
  summary: Python bindings for MMCore, Micro-Manager's device control layer
  license: LGPL-2.1 AND BSD-3-Clause
  license_file:
    - LICENSE.txt
    - MMDevice_license.txt
    - MMCore_license.txt

extra:
  recipe-maintainers:
    - goanpeca
    - marktsuchida
    - tlambert03
